### ISSUE TITLE
Elasticsearch cluster unreachable

### ISSUE THREAD

**Issue by yorchaac** [TheHive-Project/TheHiveDocs#105]
Hello! 
Someone could help me! I tried to install Thehive, I followed the steps on Thehive installation guide, and also I reviewed The issue #88, but the ports are right and all is running but when I type the URL http://my_server_Ip:9000, I get directly the login page and no allow me register a new user, If I type user : "A", password : "A" I get the same error message that  issue#88 "elasticsearch cluster unreachable", and I cant understand what is wrong.

**********This is part of my application.conf file****************

# Elasticsearch
search {
  index = the_hive
  cluster = hive
  host = ["10.10.10.2:9300"]
   keepalive = 1m
   pagesize = 50
   nbshards = 5
   nbreplicas = 1
  settings {
                   mapping.nested_fields.limit = 100
                  }
search.ssl.enabled = false
  }

*************This is my elasticsearch File .yml********************

cluster.name: hive
node.name: the_hive
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

 ---------------------------------- Network -----------------------------------
network.host: 10.10.10.2
transport.tcp.port: 9300

# --------------------------------- Discovery ----------------------------------
discovery.seed_hosts: ["10.10.10.2"]
cluster.initial_master_nodes: ["the_hive"]

**Comment by k3rnon** [comment]
hey m8!
What version of elasticsearch are You using? Ive read a lot of things about it and ppl says that You need Elasticsearch ~5.x... to run thehive. If You using higher version it wouldnt work...

**Comment by nadouani** [comment]
TheHive 3.4.0-RC1 added support to ES 6, but it's still in Beta

**Comment by yorchaac** [comment]
Thank you I change to Elastic 5.x, and now is working!!!
