### ISSUE TITLE
MISP on same machine

### ISSUE THREAD

**Issue by k3rnon** [TheHive-Project/TheHiveDocs#110]
Hello,
I want to connect thehive with the MISP but I am curious about Yours opinion. Should I use diffrent server/ computer for MISP or it doesnt metter and I can install thehive/cortex/misp on same virtual machine?
BR

**Comment by mdtro** [comment]
It is all very dependent on the utilization. I'd opt to put it on a separate machine if you are expecting alert volumes that of a typical SOC, but you could always try to put it on the same system and if load is a problem, migrate it off.

**Comment by k3rnon** [comment]
Thanks m8 for Your opinion!
