### ISSUE TITLE
installation behind the proxy

### ISSUE THREAD

**Issue by flngkttn** [TheHive-Project/TheHiveDocs#139]
Hi there

I have to install TheHive behind the proxy, which requires authentication.
OS RHEL7.6
When I try to Build the Project and run command:

./sbt clean stage

it says:
Getting org.scala-sbt sbt 1.2.8  (this may take some time)...

:: problems summary ::
:::: WARNINGS
        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

        Your proxy requires authentication.

                module not found: org.scala-sbt#sbt;1.2.8

How to resolve this?
Thanks in advance.

**Comment by LouisianaNutSack49** [comment]
If it’s me that can help I’ll be home in about 3 hours from now.

**Comment by flngkttn** [comment]
I entered proxy settings:
export SBT_OPTS="-Dhttp.proxyHost=<hostname> -Dhttp.proxyPort=8080 -Dhttp.proxyUser=<username> -Dhttp.proxyPassword=<password>"

Now when I execute:
user@machinename [TheHive] ./sbt clean stage
Getting org.scala-sbt sbt 1.2.8  (this may take some time)...

:: problems summary ::
:::: WARNINGS
                module not found: org.scala-sbt#sbt;1.2.8

        ==== local: tried

          /home/user/.ivy2/local/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml

          -- artifact org.scala-sbt#sbt;1.2.8!sbt.jar:

          /home/user/.ivy2/local/org.scala-sbt/sbt/1.2.8/jars/sbt.jar

        ==== local-preloaded-ivy: tried

          file:////home/user/.sbt/preloaded/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml

        ==== local-preloaded: tried

          file:////home/user/.sbt/preloaded/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

          -- artifact org.scala-sbt#sbt;1.2.8!sbt.jar:

          file:////home/user/.sbt/preloaded/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

          -- artifact org.scala-sbt#sbt;1.2.8!sbt.jar:

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        ==== sbt-maven-releases: tried

          https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

          -- artifact org.scala-sbt#sbt;1.2.8!sbt.jar:

          https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        ==== sbt-maven-snapshots: tried

          https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

          -- artifact org.scala-sbt#sbt;1.2.8!sbt.jar:

          https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        ==== typesafe-ivy-releases: tried

          https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml

        ==== sbt-ivy-snapshots: tried

          https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;1.2.8: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access Error: Connection refused (Connection refused) url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

        Server access Error: Connection refused (Connection refused) url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

        Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom

        Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar

        Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml

        Server access Error: Connection refused (Connection refused) url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.2.8/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;1.2.8: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/user/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 1.2.8

**Comment by flngkttn** [comment]
I put proxy settings in /etc/yum.conf file like this:

proxy=http://<Proxy-Server-IP-Address>:<Proxy_Port>
proxy_username=<Proxy-User-Name>
proxy_password=<Proxy-Password> 

This worked for me
