### ISSUE TITLE
Change application.conf for MISP connection

### ISSUE THREAD

**Issue by Fiebererdi** [TheHive-Project/TheHiveDocs#150]
Hi guys,

I tested Cortex and MISP connection. Cortex works fine, MISP struggeling with the application.conf you wrote in the example. The problem is case sensitive. MISP Part of the application.conf needs to looks like this 

```
play.modules.enabled += org.thp.thehive.connector.misp.MispModule #(mips != misp. MISPModule != MispModule)
misp {
  interval: 1 hour
  servers: [
   {
    name: "MISP-Server"          # MISP name
    url: "127.0.0.1"             # MISP URL
    auth: {
      type: "key"
      key: "XXXXXXXXXXXXXXXX"
      }
   }
  ]
}
```

**Comment by lo-chr** [comment]
I can confirm this for TheHive4, should be changed in the documentation, but in the example file as well. There is another issue where in the config-file you write "key" (but without the quotes), which leads to another parsing error.
@Fiebererdi: Thanks for your solution, that helped a lot!

**Comment by jeromeleonard** [comment]
Fixed in TH4 doc.
