### ISSUE TITLE
[QUESTION] Type of observables - definition

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/TheHiveDocs#159]
Hi,
Can someone tell were is some definition with example of observable types.
Because I have some problem with classification. VirusTotal returns name of malware, for example Trojan.Win32.XYZ. I want to add it to observable, but suggested type are FQDN or domain. What should be?

**Comment by KRUXLEX** [comment]
Any answare, suggestions?

**Comment by KRUXLEX** [comment]
@nadouani  can you help and answer?

**Comment by nadouani** [comment]
If you need to have more datatypes, you need to add them from the administration section. Once you have added the new datatypes, you will see them listed in observable creation page.

**Comment by KRUXLEX** [comment]
Hi, I know that, this is technically, But it' is a sense? I ask someone more experience. How professionally named that observable type? Or this isn't sense to use it?
