### ISSUE TITLE
API Call with Key: Resource not found by Assets controller

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/TheHiveDocs#16]
Followed the instructions for a Docker install, here:

https://github.com/CERT-BDF/TheHiveDocs/blob/master/installation/docker-guide.md

Everything inside of the web interface (with the exception of the Help menu option - I get "A client error occurred on GET /docs : Resource not found by Assets controller" ) seems to be working okay.

Using the following command (substituting my api key for the text in the command):
 
**curl -H 'Authorization: Bearer ***API*KEY***' http://127.0.0.1:9000/api/cases**

results in the following error:

**"A client error occurred on GET /api/cases : Resource not found by Assets controller"**

Any advice would be greatly appreciated.

Thanks,
Wes

**Comment by jezkerwin** [comment]
Did you ever figure this out?
I'm having the same problem?

**Comment by weslambert** [comment]
It's been a while since I've looked at this, but I don't recall it being
resolved.  I will try taking a look again when I get a chance and let you
know if I can find any type of workaround/fix.

Thanks,
Wes

**Comment by To-om** [comment]
The correct URL is http://127.0.0.1:9000/api/case (without "s" at the end)
