### ISSUE TITLE
[BUG] Not able to add new dataTypes

### ISSUE THREAD

**Issue by jsomwaru** [TheHive-Project/TheHiveDocs#165]
Hi,

I think I found a bug in the Hive4. When I sign in as an admin and navigate to: 

Admin > Obserable types

Then try to add an observable. The observable appears in in the UI on the observable types page. However, when i sign out and sign into my personal account on the hive. When trying to add observables to the case the new data types are not there.

I've look in the documentation, and open issues and I couldn't find anything that mentioned this problem.

Also in the Admin > Observable types page  I am  not able to delete added datatypes.

**Comment by KRUXLEX** [comment]
This strange, because in my instant, I don't experience any issues like that. Can you send a screenshot with issue?

**Comment by jsomwaru** [comment]
Interesting, so if you look here at the top of the list I just added the data type "actor" for testing purposes.

<img width="1901" alt="Screen Shot 2020-04-21 at 2 37 33 PM" src="https://user-images.githubusercontent.com/32558301/79901619-16664180-83de-11ea-8b02-64dc8096aaa1.png">

Then just to be safe I ran sudo systemctl restart (but I've tested both ways doesn't make the difference)

Then in separate browser on my personal account. I have a case open and try to add an observable and you can see there is not one named actor.

<img width="905" alt="Screen Shot 2020-04-21 at 2 38 20 PM" src="https://user-images.githubusercontent.com/32558301/79901858-84126d80-83de-11ea-9243-db8154a98664.png">

**Comment by KRUXLEX** [comment]
Hi, I was check it in my infrastructure. It work correctly. I was add some new observable types and all operators (not admin) can use without problems.
Something must be broken in your system.

**Comment by jsomwaru** [comment]
@KRUXLEX Thanks for responding, Could you let me know what version you are on?

**Comment by KRUXLEX** [comment]
Latest stable: 3.4.0-1

**Comment by jsomwaru** [comment]
Also took a look at the logs this is for the v4.0. 
On the admin observable page in the logs you can see the request go to
/api/observable/type?range=all
<img width="525" alt="Screen Shot 2020-04-27 at 4 07 49 PM" src="https://user-images.githubusercontent.com/32558301/80415922-3fd11280-88a1-11ea-8c3f-c2079cc378d4.png">
On the create Observable page the service goes to:
/api/list/list_artifactDataType
<img width="614" alt="Screen Shot 2020-04-27 at 4 09 23 PM" src="https://user-images.githubusercontent.com/32558301/80416042-773fbf00-88a1-11ea-8223-c21b4cc7a1fe.png">

These both return different results. The list_artifactDataType only returns the dataTypes returned by the system.

**Comment by nadouani** [comment]
Hello guys, this repo is dedicated to TheHive documentation, issues are not really tracked here, and we might not see them.

Please fill issues in TheHive's repo.

BTW this one is already there
