### ISSUE TITLE
RPM repo not working

### ISSUE THREAD

**Issue by camilodiazsal** [TheHive-Project/TheHiveDocs#185]
The RPM repository for both stable and beta versions are not accepting connections:

[thehive-project]
enabled=1
priority=1
name=TheHive-Project RPM repository
baseurl=http://rpm.thehive-project.org/stable/noarch
gpgcheck=1
 
Error:
http://rpm.thehive-project.org/stable/noarch/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to rpm.thehive-project.org:80; Connection refused"

**Comment by desnij** [comment]
this is working for me for both th4 and previous, perhaps that was a network hiccup? 

```
rpm --import   https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY

cat <<EOF> /etc/yum.repos.d/thehive4.repo
[thehive-project]
enabled=1
priority=1
name=TheHive-Project RPM repository
baseurl=http://rpm.thehive-project.org/stable/noarch
gpgcheck=1
EOF

 yum install thehive4
```

**Comment by To-om** [comment]
The repository uses https, but it is not your problem as http redirects to https.
@camilodiazsal I think you try during a maintenance period. Please try again and reopen this issue if the problem persists.

**Comment by desnij** [comment]
what I posted was from the docs. :)  but yes I am sure their issue was form a maintenance period.
merci
