### ISSUE TITLE
Content-Type usage unclear

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHiveDocs#19]
The documentation about cases:
https://github.com/CERT-BDF/TheHiveDocs/blob/master/api/case.md
does not mention when Content-Type , if it is needed (and when not).

Fails:
curl -XPOST -u user:password -H "Content-Type: application/json" "http://127.0.0.1:9000/api/case/task/_search"

Works:
curl -XPOST -u user:password -H "Content-Type: application/json" "http://127.0.0.1:9000/api/case/task/_search"  -d '{}' 
curl -XPOST -u user:password "http://127.0.0.1:9000/api/case/task/_search"

**Comment by To-om** [comment]
Hi,
Your first request fails because you specify a content type as json but you didn't provide any content. An empty content is not a valid json.
