### ISSUE TITLE
Run Analyzer in TheHive

### ISSUE THREAD

**Issue by asfandyarkhan01** [TheHive-Project/TheHiveDocs#25]
I want to run a PCAP file anaylzer, that I have developed, in theHive but I am getting the below message. While the analyzer works perfectly in Cortex. Please help me to resolve the issue.
![capture](https://user-images.githubusercontent.com/22009392/33893132-0348f536-df5b-11e7-8405-07bf65492bb2.PNG)

**Comment by nadouani** [comment]
Hello, 

1/ can you show the list of your available analyzers? 
2/ Is you Cortex up and running?

Thanks

**Comment by 3c7** [comment]
Is TheHive [properly configured](https://github.com/CERT-BDF/TheHiveDocs/blob/master/admin/configuration.md#6-cortex) to use your Cortex-Server?

**Comment by asfandyar-khan** [comment]
Thank you so much for your concern. The problem has been solved as I found an error in a configuration file.
