### ISSUE TITLE
Misp synchronization failed

### ISSUE THREAD

**Issue by kaustavbhattacharjee** [TheHive-Project/TheHiveDocs#34]
I am using the Hive Training VM  with the following configuration 

1) MISP user is given user role
2) Tags name is default "misp"
3) max date = 30 days

I have kept all the other config same as per the docs.
But still I am facing the following error (when checked from logs):
![image](https://user-images.githubusercontent.com/7832958/36012432-145c9768-0d84-11e8-9815-52594a4ae3fa.png)

Please help!

**Comment by gitQuestions** [comment]
Hello,

I have the same problem.

Any suggestion to solve the problem?

**Comment by WeaverHeavy** [comment]
@kaustavbhattacharjee Could you explain how you solved this issue?

**Comment by kaustavbhattacharjee** [comment]
Can you check if the MISP is reachable from Hive? As far I remember, I had to allow an access over http for MISP to Hive.
