### ISSUE TITLE
Debian package repo "typo"

### ISSUE THREAD

**Issue by SteveClement** [TheHive-Project/TheHiveDocs#39]
Dear,

As per install guide here: https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/deb-guide.md

adding **deb https://dl.bintray.com/cert-bdf/debian any main** to apt sources fails with a 404.

Reason, there is no **any** folder in: https://dl.bintray.com/cert-bdf/debian/dists/
only an **ny** folder: https://dl.bintray.com/cert-bdf/debian/dists/ny/

Cheers.
Steve

**Comment by 3c7** [comment]
See #36.
