### ISSUE TITLE
/bin/activator does not create /target/universal/stage

### ISSUE THREAD

**Issue by Xiobe** [TheHive-Project/TheHiveDocs#45]
am building from source on a centos7 (actually I am writing a bash script for it). The line
> sudo cp -r /opt/TheHive/target/universal/stage /opt/thehive

did not work. I have no knowledge about SBT but as far as I understood the issue the command
> bin/activator clean stage

should be
> /opt/TheHive/bin/activator clean compile stage dist

This generates for me the path that is described in the documentation.

Could this be an issue with the documentation or did I make a mistake?

**Comment by mouhcine852000** [comment]
Hi Team,

[root@localhost TheHive]# bin/activator clean stage
bash: bin/activator: No such file or directory

there is another install componnet requirement missed in the documentation ?

Thanks in advance for your help

Regards,
Mouhcine

**Comment by To-om** [comment]
I've just fixed the documentation. Activator has been removed and replaced by sbt.

**Comment by mouhcine852000** [comment]
Thank you, command in progress ;)
