### ISSUE TITLE
API Documentation about template

### ISSUE THREAD

**Issue by kkadosh** [TheHive-Project/TheHiveDocs#61]
Hy!

I was looking into your API Documentation, and i don't see how/if it's possible to create a case from a template.
If it is possible to do that through the API, is it possible to document it please ? :)

**Comment by kkadosh** [comment]
After some debugging, it's seems that we can provide the attribute `template` as below : 

```
POST /api/case HTTP/1.1
... HEADER ...

{"status":"Open","title":"test","template":"My Template"}
```

**Comment by RANGERBEE** [comment]
Oh, so I can create a template via the API??

**Comment by RANGERBEE** [comment]
sorry I see, to choose the template via the api string.  I need to create templates via api...
