### ISSUE TITLE
Need to be able to set up Roles and only allow certain roles to view certain incidents.

### ISSUE THREAD

**Issue by aaronmartin1651** [TheHive-Project/TheHiveDocs#62]
Need a way to allow certain incidents to be visible only to select users. The idea is that a person may be doing an investigation and will need to protect the incident from access by users not authorized to view the data.

**Comment by 3c7** [comment]
See https://github.com/TheHive-Project/TheHive/issues/103, that's a feature currently in work, but it takes time.
