### ISSUE TITLE
Improvement: Upload of observables fail "silently"

### ISSUE THREAD

**Issue by vlabmichl** [TheHive-Project/TheHiveDocs#79]
As an improvement to the UI / UX when dealing with "uploads of observables" it would be great if the upload would "not fail silently".

In my case I offered the wrong password to a ZIP-file.

The annoying thing is that you have to "re-enter all fields" of the upload form each time you retry your upload.

Would be more convenient if the file and the according dataset were stored on the server / database an the dataset is marked with sth like "proccessing error" if needed. Then you'd only need fix the attributes that might be false.

Especially when you're trying to do "Trial-and-Error" with passwords this would be nice to have.
;-)

**Comment by nadouani** [comment]
Is this a feature request? If yes, it should be submitted on TheHive's repo

**Comment by vlabmichl** [comment]
Sorry - moved it to thehive-project/thehive#829.
