### ISSUE TITLE
Feature "CTRL"+"Return" to submit UI forms

### ISSUE THREAD

**Issue by vlabmichl** [TheHive-Project/TheHiveDocs#80]
Using Forms would be streamlined if one could use "CTRL"+"Return" key combination to submit UI forms.

Just for the lazy...

;-)

**Comment by nadouani** [comment]
Is this a feature request? If yes, it should be submitted on TheHive's repo

**Comment by vlabmichl** [comment]
Sorry - moved it to TheHive-Project/TheHive#830.
