### ISSUE TITLE
No information about community

### ISSUE THREAD

**Issue by gudsaf** [TheHive-Project/TheHiveDocs#85]
Need info about community:
- where to ask a quick question?
- channel on slack?
- group in telegram?
- forum?
- etc..

This need to be in docs or somewhere, i think.
For now i have use case from live and i need to know does theHive with all its projects together can bring it. Where to ask about it?

**Comment by nadouani** [comment]
Well, if you just take a look to the main page of this repo, you have a support section when we explain how to join us.
