### ISSUE TITLE
Elasticsearch cluster unreachable

### ISSUE THREAD

**Issue by Include-sys** [TheHive-Project/TheHiveDocs#88]
Hello,

I installed The Hive via apt packet manager on Debian 9 Stretch.

The Hive Version: 3.2.1-1

ElasticSearch Version: 5.6.15

**Error I'm getting,**
![image](https://user-images.githubusercontent.com/10716262/53939395-f386aa00-40c3-11e9-9b6a-09e328862cd7.png)

**Elastic Search Info,**

![image](https://user-images.githubusercontent.com/10716262/53939518-57a96e00-40c4-11e9-98fd-9735898a908b.png)

**The Hive Conf(Elastic Search)**
![image](https://user-images.githubusercontent.com/10716262/53939557-7b6cb400-40c4-11e9-8ca1-d6e47067330a.png)

**ElasticSearch yml;**
`cluster.name: hive
node.name = the_hive
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0 (Also tried to 127.0.0.1)
http.port: 9200
`

**The Hive Application Log:**

![image](https://user-images.githubusercontent.com/10716262/53940332-7a3c8680-40c6-11e9-8080-d6eb1a17c330.png)

Thanks in advance.

**Comment by Include-sys** [comment]
The mistake I did,

Instead of Node port(9300) I wrote http port of elastic search to instance section in the hive conf. Issue can be closed.

**Comment by david1115-edgv** [comment]
Hello

I have the same problem, could you be a little more specific with your solution?

Thank you

**Comment by Include-sys** [comment]
@root-r-tech Hello, I wrote 0.0.0.0:9200 to host part of ElasticSearch setting in The Hive Conf file. But I should write 9300 It's the correct port. The Hive connects to Elasticsearch trough Elastic Node port which is 9300 (default) and I had a problem because I wrote 9200 (elastic default http). I hope It helps.
